### PR TITLE
Synchronize topic replicas + partitions

### LINKED ISSUE #34: Add support for increasing number of partitions in a topic
Given the following statefile:
```
#Orders
topics:
  orders:
    partitions: 5
    replication: 3
```
Desired state:
When I update partitions to 6 I expect the tool to increase the number of partitions.
Actual State:
Executing apply...
[SUCCESS] There are no necessary changes; the actual state matches the desired state.

Kafka Version -  2.1.1-cp1
Kafka-gitops version - 0.2.7

### PR DESCRIPTION
**Pull request by jrevillard**
Hello,

This PR fixes #34 + also manage replicas.

For topic config modifications and deletion also I added in output the previous value in order to have more information (I can update the way it is displayed if you want).

Best,
Jerome

### CODE REVIEW

**Comment by devshawn** [comment]
Thanks for the PR! I will review it this weekend.

**Comment by jrevillard** [comment]
Any news @devshawn ? 

Best,
Jerome

**Comment by devshawn** [comment]
Hi @jrevillard, sorry I have been out sick lately. I am adding a few tests and releasing a new version shortly; if you could rebase on that I will take a look and get this merged in this week. Thank you!!

**Comment by jrevillard** [comment]
Hi @devshawn , rebase done.

Best.

**Comment by devshawn** [comment]
Awesome. Once again, apologies for the delay. I am going to review, run some additional tests against cloud clusters (e.g. confluent cloud), and then if all looks good, merge it in and get a release out. I don't have time until the weekend but I'm finally free for a weekend and will happily get this taken care of.

Thanks again @jrevillard!

**Comment by jrevillard** [comment]
Any news @devshawn ?

Best.

**Comment by devshawn** [comment]
Apologies again! Taking a look at this and will merge it in this weekend.

**Comment by devshawn** [comment]
I've been testing it around and it seems to be working for all situations -- I'll probably do a pre-releases/snapshot of this first since its such a large change.

**Comment by jrevillard** [comment]
Hello,

Any news about it please? 

I wonder what are your plans for kafka-gitopt ? do you still plan to develop it or not ? I see a couple of very interesting missing features that can be done but if you think that you might not have any more time to develop it I might look for other solutions... 
Perhaps sharing the repository management with the community could help ?

Best,
Jerome

**Comment by sarahgudc** [comment]
Hi,

I am also curious about the future roadmap of kafka-gitops. It's a really interesting tool and I would like to adopt it into a project assuming there are ongoing plans for development. I also would find this PR a very useful feature! :)

thanks very much,

Sarah

**Comment by devshawn** [comment]
I do plan to further develop kafka-gitops as well as take in PRs from anyone :) 

I had a crazy past few months which prevented me from having time to work on projects. I have made time this weekend to review and merge this PR.

**Comment by devshawn** [comment]
All of my testing so far has been looking good. Should finally be released by the end of the weekend :)

**Comment by MartinBurian** [comment]
@devshawn I'm sorry to look like I'm pushing, but I find this tool to be the simplest gitops solution for kafka management and we're sorely missing this configuration option :disappointed: Can I help in any way to get it done? Otherwise, I would need to create a fork of kafka-gitops with this merged for our use, or, in the worst case, use Terraform for the job...

**Comment by jrevillard** [comment]
> @devshawn I'm sorry to look like I'm pushing, but I find this tool to be the simplest gitops solution for kafka management and we're sorely missing this configuration option disappointed Can I help in any way to get it done? Otherwise, I would need to create a fork of kafka-gitops with this merged for our use, or, in the worst case, use Terraform for the job...

Hello @MartinBurian , you can use my fork if you like. I also plan on the coming weeks to integrate the work of @Twb3 concerning schema registry and add JSON support.

**Comment by casimcdaniels** [comment]
@devshawn So, are we merging this or not? Please open up this project to more contributors if you're backlogged.

**Comment by devshawn** [comment]
Hi @jrevillard @casimcdaniels @MartinBurian, my apologies on the lack of support on the project. I had quite a backlog of other projects over the past few months.

I will review and merge all the pending PRs and get the latest updates pushed by the end of this weekend, I promise this time -- I have booked my calendar accordingly. We can look into opening this up to more collaborators after cleaning up the current list of PRs and issues. Thank you everyone for the contributions!!

Look forward to a release by the end of this weekend, although I plan to get to it sooner than that.

**Comment by devshawn** [comment]
Doing some more testing and hope to get a release out shortly :)

**Comment by jrevillard** [comment]
Still no news @devshawn ?

**Comment by devshawn** [comment]
@jrevillard Sorry I actually caught a case of influenza that's been keeping be down this week. I am still working on getting this out within the next week.

**Comment by JianTray** [comment]
We would also be interested in getting this PR deployed? Would be very useful for tracking our topics :)

**Comment by devshawn** [comment]
Pre-release build will be released shortly.

**Comment by JianTray** [comment]
There's an error in line 126 of KafkaService.java which is causing an index out of bounds error. The line should read:
`replicas.remove(replicas.size() - 1);`

Also getting an error with mBeam:
```WARN org.apache.kafka.common.utils.AppInfoParser - Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.admin.client:type=app-info,id=kafka-gitops
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:64)
	at org.apache.kafka.clients.admin.KafkaAdminClient.<init>(KafkaAdminClient.java:500)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:444)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:69)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:49)
	at com.devshawn.kafka.gitops.service.KafkaService.buildAdminClient(KafkaService.java:195)
	at com.devshawn.kafka.gitops.service.KafkaService.getTopicDescription(KafkaService.java:173)```
```

And the -command-config argument seems to do nothing atm :)

**Comment by irisgve** [comment]
Hi @devshawn, this particular merge doesn't seem to be included in any release yet. The latest release seems to be from Feb 2021. Are there any plans of creating a release for all the recent changes including this one? Thanks.

**Comment by dal13002** [comment]
@devshawn I believe the latest image release (ie on [dockerhub](https://github.com/devshawn/kafka-gitops)) doesn't have this change. Any plan to release a new version?

**Comment by iNviNho** [comment]
@devshawn Two years have passed and this is still not released.

You should really consider giving more people rights to manage this repository.

**Pull request merged**
