### PR TITLE
fix: added command option to skip acls

### LINKED ISSUE #51: Feature request: possibility to manage topics only
Hi,
It's a great tool.
It would be nice to have possibility to manage only kafka topics, without ACLs.

When I tried to `plan` config file with topics configuration I get this error:
> [ERROR] Error thrown when attempting to list Kafka ACLs:
> org.apache.kafka.common.errors.SecurityDisabledException: No Authorizer is configured on the broker
> [ERROR] An error has occurred during the planning process. No plan was created.

### PR DESCRIPTION
**Pull request by Cinetik**
This option is not bugging the delete feature like the closed PR. This fixes #51 
This is simply an option check to by-pass the acl if you don't have any configured

### CODE REVIEW

**Comment by devshawn** [comment]
Thanks for the PR! I will review it this weekend.

**Comment by mattzque** [comment]
I ran into some issue using this, the plan command works, but when I tried to apply it this error occured:

```
java.lang.IllegalStateException: Not set: [skipAclsDisabled]
        at com.devshawn.kafka.gitops.config.ManagerConfig_Builder.build(ManagerConfig_Builder.java:408)
        at com.devshawn.kafka.gitops.config.ManagerConfig$Builder.build(ManagerConfig.java:25)
        at com.devshawn.kafka.gitops.cli.ApplyCommand.generateStateManagerConfig(ApplyCommand.java:59)
        at com.devshawn.kafka.gitops.cli.ApplyCommand.call(ApplyCommand.java:35)                       
        at com.devshawn.kafka.gitops.cli.ApplyCommand.call(ApplyCommand.java:20)                       
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)                                
        at picocli.CommandLine.access$900(CommandLine.java:145)                                                         
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)                                                     
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)                                                     
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)                                
        at picocli.CommandLine.execute(CommandLine.java:1904)                                                                  
        at com.devshawn.kafka.gitops.MainCommand.main(MainCommand.java:69)
```

I think that's because of the generated ManagerConfig.Builder requiring a value for `skipAclsDisabled` not just for the PlanCommand but for the other Commands too. I did a [quick fix here](https://github.com/mattzque/kafka-gitops/commit/b0f5bfe41ad609abd091758b8dc6afcdbac30376), it works for me but I'm not sure if that's the right fix.

Anyhow wanted to let you guys know. Thanks for your work!

**Comment by devshawn** [comment]
Nice find, @mattzque. Thanks for the PR @Cinetik. A few thoughts...

I'm wondering since this can affect both the plan and apply, if this should be a top level flag like the `--no-delete` flag. 

```
kafka-gitops -f state.yaml --skip-acls plan
```

Right now, with this code, you could run `kafka-gitops plan` which would take into account ACLs, and then run `kafka-gitops apply --no-acls` and it would still apply ACLs since they would be in the plan file (assuming you had ACL support enabled). 

Thoughts?

**Comment by Cinetik** [comment]
A good idea, made it global like you suggested

**Comment by Cinetik** [comment]
@devshawn Any chance you can get a look at it this week?

**Comment by jpdias92** [comment]
Nice addition @Cinetik, I've just started experimenting with this tool and was having the same issue with ACLs in my playground Kafka cluster with no authentication, using your branch with the new flag I was able to keep experimenting with the tool just for topic management.

I confirm it worked fine for me, both `apply` and `plan`.

Just a small comment, not sure if there's some automated process to update the docs with the usage screen, if not, you should update the usage documentation to include the new flag.

Thanks for your work!

**Comment by devshawn** [comment]
@Cinetik - I'll take care of this today. Great work!!!

**Comment by Cinetik** [comment]
Hey, hope you're doing great!
I was hoping to get some update on this PR this week. 
Anything I can help with?

**Comment by devshawn** [comment]
@Cinetik Sorry! I got sick last week and was not on my computer much. I'll have a new release put out tonight, this looks great, thanks again!

**Review by devshawn — APPROVED** [review]

**Pull request merged**
