### PR TITLE
feat: Load Kafka connection config from properties file

### LINKED ISSUE #65: Feature: get connection config from file
Reading Kafka connection config from environment variables is alright when using Docker.

But when running kafka-gitops without Docker (makes me sad), setting environment variables may reveal passwords to anyone being able to read `/prod<pid>/environ`

Being able to provide an `admin.properties` file containing Admin client settings would be very useful.

### PR DESCRIPTION
**Pull request by gquintana**
Fixes #65

### CODE REVIEW

**Comment by devshawn** [comment]
Thank you for the contribution! I will review it shortly and include it in the next release. 🚀

**Comment by dberuben** [comment]
Any update on that? i'm interested?

**Comment by sunny092318** [comment]
Any update on this ..

**Review by devshawn — APPROVED** [review]

**Comment by devshawn** [comment]
Pre-release build will be released shortly! Apologies for the wait.

**Pull request merged**
